package cu.fcc.pigeon.config;

public final class SYSMensaje {

    /**
     * MENSAJE GENERICO SI HAY PROBLEMAS CON LA CONEXION A LA BD
     */
    public static final String DB_CONECTION = "POR FAVOR INTENTE MAS TARDE HAY PROBLEMAS DE CONEXION CON LA BASE DE DATOS";

    /**
     * AQUI LAS VARIABLES MENSAJE DE PARADERO
     */
    public static final String PARADERO_NOMBRE = "EN LA SOCIEDAD YA EXISTE UN PARADERO CON NOMBRE: ";
    public static final String PARADERO_NOSOCIEDAD = "NO EXISTE SOCIEDAD CON ID: ";
    public static final String PARADERO_INSERT_OK = "PARADERO INSERTADO CORRECTAMENTE: ";
    public static final String PARADERO_UPDATE_OK = "PARADERO ACTUALIZADO CORRECTAMENTE: ";
    public static final String PARADERO_EXISTS = "PARADERO OBTENIDO SATISFACTORIAMENTE: ";
    public static final String PARADERO_NOEXISTS = "NO EXISTE UN PARADERO CON ID: ";
    public static final String PARADERO_LIST = "LISTADO DE PARADEROS PARA LA SOCIEDAD CON ID: ";
    public static final String PARADERO_NOLIST = "NO EXISTE LISTADO DE PARADEROS PARA LA SOCIEDAD CON ID: ";

    /**
     *  AQUI LOS MENSAJES DE SOCIEDAD
     */

    public static final String SOCIEDAD_NOMBRE = "EN EL MUNICIPIO YA EXISTE UNA SOCIEDAD CON NOMBRE: ";
    public static final String SOCIEDAD_NOMUNICIPIO = "NO EXISTE MUNICIPIO CON ID: ";
    public static final String SOCIEDAD_INSERT_OK = "SOCIEDAD INSERTADA CORRECTAMENTE: ";
    public static final String SOCIEDAD_UPDATE_OK = "SOCIEDAD ACTUALIZADA CORRECTAMENTE: ";
    public static final String SOCIEDAD_EXISTS = "SOCIEDAD OBTENIDA SATISFACTORIAMENTE: ";
    public static final String SOCIEDAD_NOEXISTS = "NO EXISTE UNA SOCIEDAD CON ID: ";
    public static final String SOCIEDAD_LIST = "LISTADO DE SOCIEDADES PARA EL MUNICIPIO CON ID: ";
    public static final String SOCIEDAD_NOLIST = "NO EXISTE LISTADO DE SOCIEDADES PARA EL MUNICIPIO CON ID: ";

    /**
     * VUELO
     */
    public static final String VUELO_INSERT_OK = "VUELO INSERTADO CORRECTAMENTE: ";
    public static final String VUELO_INSERT_COLOMBOFILO_OK = "COLOMBOFILO AGREGADO AL VUELO CORRECTAMENTE: ";
    public static final String VUELO_UPDATE_OK = "VUELO ACTUALIZADO CORRECTAMENTE: ";
    public static final String VUELO_EXISTS = "VUELO OBTENIDO SATISFACTORIAMENTE: ";
    public static final String VUELO_NOEXISTS = "NO EXISTE UN VUELO CON ID: ";
    public static final String VUELO_NOEXISTS_ENVIADAS = "NO HAY PALOMAS ENVIADAS PARA EL VUELO CON ID: ";
    public static final String VUELO_LIST = "LISTADO DE VUELOS PARA EL PARADERO CON ID: ";
    public static final String VUELO_NOLIST = "NO EXISTE LISTADO DE VUELOS PARA EL PARADERO CON ID: ";
    public static final String VUELO_CALCULATE_VELOCIDAD = "CALCULO DE VELICIDADES PARA EL VUELO EFECTUADO CORRECTAMENTE";
    public static final String VUELO_CALCULATE_PUNTOS = "PUNTOS REPARTIDOS PARA EL VUELO CORRECTAMENTE";
    public static final String VUELO_NOCOLOMBOFILOS = "NO HAY COLOMBOFILOS RESGISTRADOS EN EL VUELO";
    public static final String VUELO_COLOMBOFILOS_EXISTS = "EL COLOMBOFILO YA EXISTE EN EL VUELO: ";
    public static final String VUELO_COLOMBOFILOS_NOEXISTS = "NO EXISTE EL COLOMBOFILO-VUELO CON ID: ";
    public static final String VUELO_COLOMBOFILOS_INSERT = "COLOMBOFILO AGREGADO AL VUELO CORRECTAMENTE ";
    public static final String VUELO_COLOMBOFILOS_APERTURA = "EL HORARIO DE APERTURA NO PUEDE SER MAYOR QUE LOS CIERRES ";
    public static final String VUELO_COLOMBOFILOS_FECHAS = "DEBE LLENAR TODOS LOS CAMPOS DE APERTURA Y CIERRES";
    public static final String VUELO_COLOMBOFILOS_UPDATE = "COLOMBOFILO ACTUALIZADO EN EL VUELO CORRECTAMENTE";

    /**
     * COLOMBOFILO_VUELO
     */

    public static final String COLOMBOFILOS_VUELO_EXISTS = "COLOMBOFILO_VUELO OBTENIDO CORRECTAMENTE";
    public static final String COLOMBOFILOS_VUELO_NOEXISTS = "NO EXISTE COLOMBOFILO_VUELO";

    /**
     * COLOMBOFILO
     */

    public static final String COLOMBOFILO_CI = "EN SOCIEDAD YA EXISTE UN COLOMBOFILO CON CI: ";
    public static final String COLOMBOFILO_INSERT_OK = "COLOMBOFILO INSERTADO CORRECTAMENTE: ";
    public static final String COLOMBOFILO_UPDATE_OK = "COLOMBOFILO ACTUALIZADO CORRECTAMENTE: ";
    public static final String COLOMBOFILO_EXISTS = "COLOMBOFILO OBTENIDO SATISFACTORIAMENTE: ";
    public static final String COLOMBOFILO_NOEXISTS = "NO EXISTE UN COLOMBOFILO CON ID: ";
    public static final String COLOMBOFILO_LIST = "LISTADO DE COLOMBOFILOS PARA LA SOCIEDAD CON ID: ";
    public static final String COLOMBOFILO_NOLIST = "NO EXISTE LISTADO DE COLOMBOFILOS PARA LA SOCIEDAD CON ID: ";

    /**
     * PALOMA
     */

    public static final String PALOMA_IDENT = "YA EXISTE UNA PALOMA CON ESA ANILLA, AÑO Y PAIS: ";
    public static final String PALOMA_COLOR = "NO EXISTE UN COLOR CON ID: ";
    public static final String PALOMA_INSERT_OK = "PALOMA INSERTADA CORRECTAMENTE: ";
    public static final String PALOMA_UPDATE_OK = "PALOMA ACTUALIZADA CORRECTAMENTE: ";
    public static final String PALOMA_EXISTS = "PALOMA OBTENIDA SATISFACTORIAMENTE: ";
    public static final String PALOMA_NOEXISTS = "NO EXISTE UNA PALOMA CON ID: ";
    public static final String PALOMA_LIST = "LISTADO DE PALOMAS PARA EL COLOMBOFILO CON ID: ";
    public static final String PALOMA_NOLIST = "NO EXISTE LISTADO DE PALOMAS PARA EL COLOMBOFILO CON ID: ";

    /**
     * PREMIO
     */

    public static final String PREMIO_IDENT = "LA PALOMA YA SE ENCUENTRA REGISTRADA EN EL VUELO: ";
    public static final String PREMIO_INSERT_OK = "PREMIO INSERTADO CORRECTAMENTE: ";
    public static final String PREMIO_UPDATE_OK = "PREMIO ACTUALIZADO CORRECTAMENTE: ";
    public static final String PREMIO_EXISTS = "PREMIO OBTENIDO SATISFACTORIAMENTE: ";
    public static final String PREMIO_NOEXISTS = "NO EXISTE UN PREMIO CON ID: ";
    public static final String PREMIO_LIST_PALOMA = "LISTADO DE PREMIO PARA LA PALOMA CON ID: ";
    public static final String PREMIO_NOLIST_PALOMA = "NO EXISTE LISTADO DE PREMIO PARA LA PALOMA CON ID: ";
    public static final String PREMIO_LIST_VUELO = "LISTADO DE PREMIO PARA EL VUELO CON ID: ";
    public static final String PREMIO_NOLIST_VUELO = "NO EXISTE LISTADO DE PREMIO PARA EL VUELO CON ID: ";
    public static final String PREMIO_ID_VUELO_EMPTY = "EL ID DEL VUELO NO PUEDE SER VACIO, NULL o MENOR QUE CERO: ";
}
